### PR TITLE
Added check for if rep_call is missing

### LINKED ISSUE #89: [BUG] Screenshot capture only-on-failure crashes if an exception is raised during setup
Trace:

```
        screenshot_option = pytestconfig.getoption("--screenshot")
        capture_screenshot = screenshot_option == "on" or (
>               request.node.rep_call.failed and screenshot_option == "only-on-failure"
        )
E       AttributeError: 'Function' object has no attribute 'rep_call'
```

The issue stems from the pytest_runtest_makereport hook
```
@pytest.hookimpl(tryfirst=True, hookwrapper=True)
def pytest_runtest_makereport(item: Any) -> Generator[None, Any, None]:
    # execute all other hooks to obtain the report object
    outcome = yield
    rep = outcome.get_result()

    # set a report attribute for each phase of a call, which can
    # be "setup", "call", "teardown"

    setattr(item, "rep_" + rep.when, rep)
```

During execution of a test, this hook once each for setup, call, and teardown. When a test has completed, the item will have 3 attributes: `rep_setup`, `rep_call`, `rep_teardown`

If execution halts due to an exception within a fixture before the test code is executed, then the item will only have a `rep_setup` attribute. So the following line, which checks for node.rep_call, fails:
```
        capture_screenshot = screenshot_option == "on" or (
            request.node.rep_call.failed and screenshot_option == "only-on-failure"
        )
```

There are a couple of ways I thought of to solve this:
1. Perform a cascading check for reach `rep_x` attribute and retrieve the `failed` attribute from the latest one.
2. If the only use for the report is to check the failure state of the current test loop regardless of phase, then the report hook could be modified like so:
```
@pytest.hookimpl(tryfirst=True, hookwrapper=True)
def pytest_runtest_makereport(item: Any) -> Generator[None, Any, None]:
    # execute all other hooks to obtain the report object
    outcome = yield
    # Set a report attribute for the latest phase of the call, which can
    # be "setup", "call", "teardown
    item.report = outcome.get_result()

```
and then modify the capture_screenshot check in the context yield:
```
        capture_screenshot = screenshot_option == "on" or (
            request.node.report.failed and screenshot_option == "only-on-failure"
        )
```

Let me know if you need any more info.

### PR DESCRIPTION
**Pull request by shadowwolf899**
Added a simple check to see if `request.node` is missing the `rep_call` attribute, and assume the test failed if it is missing. This should hopefully fix #89

### CODE REVIEW

**Comment by mxschmitt** [comment]
do you know why this happens or what causes it? would be great if we could test it as well.

**Comment by shadowwolf899** [comment]
It seems to occur when an interrupt occurs while a test is running (for example `KeyboardInterrupt` when someone tries to cancel the test run). pytest for some reason skips `pytest_runtest_makereport`, and just goes straight to trying to close the context fixture. This code seems to make it happen reliably:
```
def test_rep_call(page):
    page.goto('https://google.com')
    raise KeyboardInterrupt
```

**Comment by mxschmitt** [comment]
Hey @shadowwolf899, I was able to add a test for it: https://github.com/microsoft/playwright-pytest/pull/98

Would be awesome if you could rebase and fix the other tests which are failing, probably the same reason.

**Comment by shadowwolf899** [comment]
I went ahead and rebased, removed the xfail, and had to switch to a try except block as for some reason the getattr was causing errors on passing tests

**Review by mxschmitt — APPROVED** [review]

**Comment by mxschmitt** [comment]
I went ahead and fixed the PR (there was a typo and replaced the try/catch by a `hasattr`). Will release a new version shortly.

**Pull request merged**
