### PR TITLE
feat: snapshot testing

### PR DESCRIPTION
**Pull request by kumaraditya303**
Closes https://github.com/microsoft/playwright-pytest/issues/63

### CODE REVIEW

**Comment by kumaraditya303** [comment]
@mxschmitt  This is ready for review

**Comment by mxschmitt** [comment]
Since there is not a high demand in that feature we would wait implementing it. I would recommend to e.g. publish a 3rd-package instead until we add it into pytest-playwright and have a better idea about the API design.

**Comment by kumaraditya303** [comment]
I wonder what is the concrete "high demand" mean here as there is an open feat request with 4 :+1: https://github.com/microsoft/playwright-pytest/issues/63 and there has been multiple requests for this on main repo.

Requests : https://github.com/microsoft/playwright-pytest/issues/63, https://github.com/microsoft/playwright-python/issues/837, https://github.com/microsoft/playwright-python/issues/775

Can specify explicitly what "high demand" mean in terms of :+1: or something concrete ?

**Comment by utapyngo** [comment]
Please implement this feature, I demand!

**Comment by utapyngo** [comment]
@kumaraditya303 could you please publish your package on PyPI?

**Comment by kumaraditya303** [comment]
> @kumaraditya303 could you please publish your package on PyPI?

Yeah here is the repo you can install it from the readme instructions until I publish it on PyPI  , I will publish it today on PyPI 

https://github.com/kumaraditya303/pytest-playwright-snapshot

**Comment by kumaraditya303** [comment]
@mxschmitt As there is high demand for this IMO this can be merged now

**Pull request closed without merging**
