### PR TITLE
(feat) make available artifacts path in test request

### PR DESCRIPTION
**Pull request by mnovait**
so they can easily be accessed to create custom test reports

### CODE REVIEW

**Comment by mnovait** [comment]
hey @mxschmitt is this plugin open for contributions?

**Comment by mnovait** [comment]
> Yes, but we usually start with an issue/feature-request, explain the use-case, elaborate on workarounds etc. Do you mind filing a feature request?

yep, totally ok with it. 
how can I open it? creating a [new issue](https://github.com/microsoft/playwright-pytest/issues/new)?

**Comment by mxschmitt** [comment]
Yes

**Comment by mnovait** [comment]
> Yes



> Yes

here it is https://github.com/microsoft/playwright-pytest/issues/247

**Pull request closed without merging**
